#Requires -Version 5.1
<#
.SYNOPSIS
  Builds Inno Setup 6 installer for HonorKitchen demo.

.DESCRIPTION
  1) Package the game (Tools\PackageWindowsShipping.ps1 or UE Package Project).
  2) Point to the packaged Windows folder:
     - Tools\installer_game_source_path.txt (one line, full path)
     - or -GameSource "D:\...\Build\Packaged\Windows"

  Output: Dist\HonorKitchen_Demo_Setup_<version>.exe

.EXAMPLE
  .\Tools\BuildInstaller.ps1 -GameSource "D:\Builds\MyProject\Build\Packaged\Windows"
#>
param(
    [Parameter(Mandatory = $false)]
    [string] $GameSource = ""
)

$ErrorActionPreference = "Stop"
# ASCII-only strings: Windows PowerShell 5.1 may mis-parse UTF-8 Cyrillic in .ps1 files.

$Root = Split-Path $PSScriptRoot -Parent
if (-not (Test-Path (Join-Path $Root "MyProject.uproject"))) {
    Write-Error "MyProject.uproject not found next to Tools. Root=$Root"
}

$pathFile = Join-Path $PSScriptRoot "installer_game_source_path.txt"
if (-not $GameSource -and (Test-Path $pathFile)) {
    $lines = @(Get-Content $pathFile -Encoding UTF8 | Where-Object { $_ -match "\S" -and $_ -notmatch "^\s*;" })
    if ($lines.Count -ge 1) {
        $GameSource = "$($lines[0])".Trim().Trim('"')
    }
}

if (-not $GameSource) {
    $defaultWin = Join-Path $Root "Build\Packaged\Windows"
    $defaultNoEd = Join-Path $Root "Build\Packaged\WindowsNoEditor"
    if (Test-Path (Join-Path $defaultWin "MyProject.exe")) {
        $GameSource = $defaultWin
        Write-Host "Auto-detected packaged build: $GameSource" -ForegroundColor DarkGray
    } elseif (Test-Path (Join-Path $defaultNoEd "MyProject.exe")) {
        $GameSource = $defaultNoEd
        Write-Host "Auto-detected packaged build: $GameSource" -ForegroundColor DarkGray
    }
}

if (-not $GameSource) {
    Write-Host @"
Packaged game folder not set (Windows folder with MyProject.exe).

Option A: create file
  $pathFile
One non-comment line = full path, e.g.:
  D:\vlads\Documents\Unreal Projects\HonorKitchen3\MyProject\Build\Packaged\Windows

Copy and edit example:
  copy Tools\installer_game_source_path.example.txt Tools\installer_game_source_path.txt

Option B:
  .\Tools\BuildInstaller.ps1 -GameSource "D:\path\to\Build\Packaged\Windows"
"@ -ForegroundColor Yellow
    exit 1
}

$gameRoot = $GameSource.TrimEnd('\').TrimEnd('/')
if (-not (Test-Path $gameRoot)) {
    Write-Error "Folder not found: $gameRoot"
}
$exe = Join-Path $gameRoot "MyProject.exe"
if (-not (Test-Path $exe)) {
    Write-Warning "MyProject.exe not found - check this is the packaged Windows folder. Path: $gameRoot"
}

$exeItem = Get-Item $exe -ErrorAction SilentlyContinue
$stampPath = Join-Path $PSScriptRoot "installer_package_stamp.txt"
$exeTime = if ($exeItem) { $exeItem.LastWriteTime.ToString('yyyy-MM-dd HH:mm:ss') } else { 'missing' }
$exeSize = if ($exeItem) { $exeItem.Length } else { 0 }
$stampLines = @(
    "Installer file source (generated by BuildInstaller.ps1)",
    "Folder: $gameRoot",
    "MyProject.exe: $exeTime",
    "Exe size (bytes): $exeSize",
    "Installer build time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
    "",
    "If the installed game is stale, you packaged to a different folder than installer_game_source_path.txt.",
    "Re-run PackageWindowsShipping.ps1 or update Tools\installer_game_source_path.txt"
)
$stampLines | Set-Content -Path $stampPath -Encoding UTF8

Write-Host ""
Write-Host "========== INSTALLER SOURCE ==========" -ForegroundColor Yellow
Write-Host "Game folder: $gameRoot" -ForegroundColor Cyan
if ($exeItem) {
    Write-Host "MyProject.exe last modified: $($exeItem.LastWriteTime)" -ForegroundColor Cyan
}
Write-Host "Stamp written: $stampPath" -ForegroundColor DarkGray
Write-Host "After install, see BUILD_FROM_INSTALLER.txt in the game folder." -ForegroundColor DarkGray
Write-Host "====================================" -ForegroundColor Yellow
Write-Host ""

$gameRootFwd = $gameRoot -replace '\\', '/'

$candidates = @(
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "$env:ProgramFiles\Inno Setup 6\ISCC.exe"
)
$iscc = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $iscc) {
    Write-Error "ISCC.exe not found. Install Inno Setup 6: https://jrsoftware.org/isdl.php"
}

$dist = Join-Path $Root "Dist"
New-Item -ItemType Directory -Force -Path $dist | Out-Null

$iss = Join-Path $PSScriptRoot "InnoSetup_MyProject_Demo.iss"
$distFwd = $dist -replace '\\', '/'

Write-Host "ISCC: $iscc"
Write-Host "ISS:  $iss"
Write-Host "Game: ${gameRootFwd}/*"
Write-Host "Out:  $dist"

$defineGame = '/DGameSourceDir="' + $gameRootFwd + '/*"'
$defineOut = '/O"' + $distFwd + '"'

& $iscc $defineGame $defineOut $iss
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

Get-ChildItem $dist -Filter "*.exe" | ForEach-Object { Write-Host "OK: $($_.FullName)" -ForegroundColor Green }
